version: '3.8'

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    container_name: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - APACHE_DISABLE_REWRITE_IP=1
    env_file: .env
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
    ports:
      - 8080:80
    env_file: .env
