version: '3.8'

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    container_name: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - APACHE_DISABLE_REWRITE_IP=1
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
