version: '3.8'

volumes:
  mariadb:
  nextcloud:

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - APACHE_DISABLE_REWRITE_IP=1
    env_file: .env
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=mariadb
    env_file: .env
    restart: always
