version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./conf:/etc/nginx/conf.d:Z
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
