version: '3.8'

services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9
    environment:
      - BIND9_USER=root
      - TZ=Australia/Darwin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    volumes:
      - ./config:/etc/bind
    restart: unless-stopped
