version: '3'

services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Australia/Darwin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind:Z
      - ./cache:/var/cache/bind:Z
      - ./records:/var/lib/bin:Z
