version: '3'
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Darwin
      - URL=${URL}
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - EMAIL=${EMAIL}
    volumes:
      - ./swagdata:/config:Z 
    ports:
      - 443:443
      - 80:80
