version: '3.5'
services:
  monerod:
    image: sethsimmons/simple-monerod:latest
    restart: always
    container_name: monerod
    volumes:
      - bitmonero:/home/monero
    ports:
      - 18080:18080
      - 18083:18083
      - 18089:18089
    command: >-
      --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=18089
      --public-node --no-igd --enable-dns-blocklist --prune-blockchain
      --zmq-pub=tcp://0.0.0.0:18083 --in-peers=50 --out-peers=50      

  p2pool:
    image: sethsimmons/p2pool:latest
    restart: unless-stopped
    container_name: p2pool
    tty: true
    stdin_open: true
    volumes:
      - p2pool-data:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    ports:
      - 3333:3333
      - 37889:37889
    command: >-
      --wallet "43vhiZ2vGX8DKkY6sorAUHBJBUT32DvmxPaLySxg8L8ePsEBQWn6hGc9rwKB6UbogHRgFYaDZ3QaVQGEz2M1zjtCUpEMKYm"
      --stratum "0.0.0.0:3333" --p2p "0.0.0.0:37889" 
      --loglevel "0" --addpeers "65.21.227.114:37889,node.sethforprivacy.com:37889"
      --host "monerod" --rpc-port "18089"      

  tor:
    image: goldy/tor-hidden-service:latest
    container_name: tor
    restart: unless-stopped
    links:
      - monerod
      - p2pool
    environment:
      MONEROD_TOR_SERVICE_HOSTS: 18089:monerod:18089
      MONEROD_TOR_SERVICE_VERSION: '3'
      P2POOL_TOR_SERVICE_HOSTS: 3333:p2pool:3333
      P2POOL_TOR_SERVICE_VERSION: '3'
    volumes:
      - tor-keys:/var/lib/tor/hidden_service/

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    bitmonero:
    tor-keys:
    p2pool-data:
